<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-push-3">
      <form class="form-group" method="post" action="jouer.php">

        <label for="name">Nom du personnage :</label>
        <input type="text" name="nom" class="form-control" required/>
        <label for="forcePerso">Force du personnage</label>
        <select class="form-control" name="forcePerso">
          <option value="20">Petite</option>
          <option value="50">Moyenne</option>
          <option value="80">Grande</option>
        </select>
        <label for="degats">Santé du personnage</label>
        <select class="form-control" name="degats">
          <option value="100">100 pts</option>
          <option value="150">150 pts</option>
          <option value="200">200</option>
        </select>


        <button type="submit" name="inserer" class="btn btn-default">Créer Perso</button>

      </form>
    </div>
  </div>
</div>
